{
	"eventos":[
		{
			"criador":"",
			"titulo":"evento1",
			"dataHoraEvento":"10/08/2018",
			"local":"",
			"categorias":["bla"]
		},
		{
			"criador":"",
			"titulo":"evento2",
			"dataHoraEvento":"10/08/2018",
			"local":"",
			"categorias":["bla"]
		},
		{
			"criador":"",
			"titulo":"evento3",
			"dataHoraEvento":"10/08/2018",
			"local":"",
			"categorias":["ble", "bli"]
		},
		{
			"criador":"",
			"titulo":"evento4",
			"dataHoraEvento":"10/08/2018",
			"local":"",
			"categorias":["bla","ble"]
		},
		{
			"criador":"",
			"titulo":"evento5",
			"dataHoraEvento":"10/08/2018",
			"local":"",
			"categorias":["blo","blu"]
		},
		{
			"criador":"",
			"titulo":"evento6",
			"dataHoraEvento":"10/08/2018",
			"local":"",
			"categorias":["bla","blo"]
		},
		{
			"criador":"",
			"titulo":"evento7",
			"dataHoraEvento":"10/08/2018",
			"local":"",
			"categorias":["bla","blu"]
		},
		{
			"criador":"",
			"titulo":"evento8",
			"dataHoraEvento":"10/08/2018",
			"local":"",
			"categorias":["bli","bla"]
		},
		{
			"criador":"",
			"titulo":"evento9",
			"dataHoraEvento":"10/08/2018",
			"local":"",
			"categorias":["bla","ble"]
		},
		{
			"criador":"",
			"titulo":"evento10",
			"dataHoraEvento":"10/08/2018",
			"local":"",
			"categorias":["ble"]
		},
		{
			"criador":"",
			"titulo":"evento11",
			"dataHoraEvento":"10/08/2018",
			"local":"",
			"categorias":["bla","ble"]
		},
		{
			"criador":"",
			"titulo":"evento12",
			"dataHoraEvento":"10/08/2018",
			"local":"",
			"categorias":["bli","blu"]
		},
		{
			"criador":"",
			"titulo":"evento13",
			"dataHoraEvento":"10/08/2018",
			"local":"",
			"categorias":["asda","ble"]
		}
	]
}